apiVersion: v1
kind: ServiceAccount
metadata:
  name: eda-saga-sa
  namespace: eda-saga
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-to-sa
subjects:
  - kind: ServiceAccount
    name: eda-saga-sa
    namespace: eda-saga
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin