apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: eda-saga-orders
  namespace: cp4i-eventstreams
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1 
  replicas: 3

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: eda-saga-reefers
  namespace: cp4i-eventstreams
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 1
    cleanup.policy: compact
    delete.retention.ms: 86400000

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: eda-saga-voyages
  namespace: cp4i-eventstreams
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 1
    cleanup.policy: compact
    delete.retention.ms: 86400000
